In [1]:
import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv('SolarPrediction_time_aligned.csv',engine='python')
dataset.head(5)

,UNIXTime,Data,Time,Radiation,Temperature,Pressure,Humidity,WindDirection(Degrees),Speed,TimeSunRise,TimeSunSet
0,8,9/1/2016 12:00:00 AM,00:00:08,2.58,51,30.43,103,77.27,11.25,06:07:00,18:38:00
1,310,9/1/2016 12:00:00 AM,00:05:10,2.83,51,30.43,103,153.44,9.00,06:07:00,18:38:00
2,1206,9/1/2016 12:00:00 AM,00:20:06,2.16,51,30.43,103,142.04,7.87,06:07:00,18:38:00
3,1505,9/1/2016 12:00:00 AM,00:25:05,2.21,51,30.43,103,144.12,18.00,06:07:00,18:38:00
4,1809,9/1/2016 12:00:00 AM,00:30:09,2.25,51,30.43,103,67.42,11.25,06:07:00,18:38:00

In [4]:
i=60
dataset[dataset=='06:07:00']=22020
dataset[dataset=='06:08:00']=22020+i
dataset[dataset=='06:09:00']=22020+2*i
dataset[dataset=='06:10:00']=22020+3*i
dataset[dataset=='06:11:00']=22020+4*i
dataset[dataset=='06:12:00']=22020+5*i
dataset[dataset=='06:13:00']=22020+6*i
dataset[dataset=='06:14:00']=22020+7*i
dataset[dataset=='06:15:00']=22020+8*i
dataset[dataset=='06:16:00']=22020+9*i
dataset[dataset=='06:17:00']=22020+10*i
dataset[dataset=='06:18:00']=22020+11*i
dataset[dataset=='06:19:00']=22020+12*i
dataset[dataset=='06:20:00']=22020+13*i
dataset[dataset=='06:21:00']=22020+14*i
dataset[dataset=='06:22:00']=22020+15*i
dataset[dataset=='06:23:00']=22020+16*i
dataset[dataset=='06:24:00']=22020+17*i
dataset[dataset=='06:25:00']=22020+18*i
dataset[dataset=='06:26:00']=22020+19*i
dataset[dataset=='06:27:00']=22020+20*i
dataset[dataset=='06:28:00']=22020+21*i
dataset[dataset=='06:29:00']=22020+22*i
dataset[dataset=='06:30:00']=22020+23*i
dataset[dataset=='06:31:00']=22020+24*i
dataset[dataset=='06:32:00']=22020+25*i
dataset[dataset=='06:33:00']=22020+26*i
dataset[dataset=='06:34:00']=22020+27*i
dataset[dataset=='06:35:00']=22020+28*i
dataset[dataset=='06:36:00']=22020+29*i
dataset[dataset=='06:37:00']=22020+30*i
dataset[dataset=='06:38:00']=22020+31*i
dataset[dataset=='06:39:00']=22020+32*i
dataset[dataset=='06:40:00']=22020+33*i
dataset[dataset=='06:41:00']=22020+34*i
dataset[dataset=='06:42:00']=22020+35*i
dataset[dataset=='06:43:00']=22020+36*i
dataset[dataset=='06:44:00']=22020+37*i
dataset[dataset=='06:45:00']=22020+38*i
dataset[dataset=='06:46:00']=22020+39*i
dataset[dataset=='06:47:00']=22020+40*i
dataset[dataset=='06:48:00']=22020+41*i
dataset[dataset=='06:49:00']=22020+42*i
dataset[dataset=='06:50:00']=22020+43*i
dataset[dataset=='06:51:00']=22020+44*i
dataset[dataset=='06:52:00']=22020+45*i
dataset[dataset=='06:53:00']=22020+46*i
dataset[dataset=='06:54:00']=22020+47*i
dataset[dataset=='06:55:00']=22020+48*i
dataset[dataset=='06:56:00']=22020+49*i
dataset[dataset=='06:57:00']=22020+50*i
dataset[dataset=='06:58:00']=22020+51*i

In [28]:
dataset[dataset=='18:38:00']=67080
dataset[dataset=='18:37:00']=67080-i
dataset[dataset=='18:36:00']=67080-2*i
dataset[dataset=='18:35:00']=67080-3*i
dataset[dataset=='18:34:00']=67080-4*i
dataset[dataset=='18:33:00']=67080-5*i
dataset[dataset=='18:32:00']=67080-6*i
dataset[dataset=='18:31:00']=67080-7*i
dataset[dataset=='18:30:00']=67080-8*i
dataset[dataset=='18:29:00']=67080-9*i
dataset[dataset=='18:28:00']=67080-10*i
dataset[dataset=='18:27:00']=67080-11*i
dataset[dataset=='18:26:00']=67080-12*i
dataset[dataset=='18:25:00']=67080-13*i
dataset[dataset=='18:24:00']=67080-14*i
dataset[dataset=='18:23:00']=67080-15*i
dataset[dataset=='18:22:00']=67080-16*i
dataset[dataset=='18:21:00']=67080-17*i
dataset[dataset=='18:20:00']=67080-18*i
dataset[dataset=='18:19:00']=67080-19*i
dataset[dataset=='18:18:00']=67080-20*i
dataset[dataset=='18:17:00']=67080-21*i
dataset[dataset=='18:16:00']=67080-22*i
dataset[dataset=='18:15:00']=67080-23*i
dataset[dataset=='18:14:00']=67080-24*i
dataset[dataset=='18:13:00']=67080-25*i
dataset[dataset=='18:12:00']=67080-26*i
dataset[dataset=='18:11:00']=67080-27*i
dataset[dataset=='18:10:00']=67080-28*i
dataset[dataset=='18:09:00']=67080-29*i
dataset[dataset=='18:08:00']=67080-30*i
dataset[dataset=='18:07:00']=67080-31*i
dataset[dataset=='18:06:00']=67080-32*i
dataset[dataset=='18:05:00']=67080-33*i
dataset[dataset=='18:04:00']=67080-34*i
dataset[dataset=='18:03:00']=67080-35*i
dataset[dataset=='18:02:00']=67080-36*i
dataset[dataset=='18:01:00']=67080-37*i
dataset[dataset=='18:00:00']=67080-38*i
dataset[dataset=='17:59:00']=67080-39*i
dataset[dataset=='17:58:00']=67080-40*i
dataset[dataset=='17:57:00']=67080-41*i
dataset[dataset=='17:56:00']=67080-42*i
dataset[dataset=='17:55:00']=67080-43*i
dataset[dataset=='17:54:00']=67080-44*i
dataset[dataset=='17:53:00']=67080-45*i
dataset[dataset=='17:52:00']=67080-46*i
dataset[dataset=='17:51:00']=67080-47*i
dataset[dataset=='17:50:00']=67080-48*i
dataset[dataset=='17:49:00']=67080-49*i
dataset[dataset=='17:48:00']=67080-50*i
dataset[dataset=='17:47:00']=67080-51*i
dataset[dataset=='17:46:00']=67080-52*i
dataset[dataset=='17:45:00']=67080-53*i
dataset[dataset=='17:44:00']=67080-54*i
dataset[dataset=='17:43:00']=67080-55*i
dataset[dataset=='17:42:00']=67080-56*i

In [29]:
test=dataset["TimeSunSet"]

In [22]:
print(test[528])
print(test[529])
print(test[529]-test[528])
if test[529]!=test[528]:
    print("rrr")

22020
22080
60
rrr

In [25]:
j=0
for j in range(0,len(test)-1):
    if test[i+1]!=test[i]:
        print(j)

In [30]:
value=0
j=0
for j in range(0,len(test)-1):
    value=value+test[j+1]-test[j]
    #print(j)

print(value)

-2640

In [31]:
print(test)

0        67080
1        67080
2        67080
3        67080
4        67080
         ...
32681    64440
32682    64440
32683    64440
32684    64440
32685    64440
Name: TimeSunSet, Length: 32686, dtype: object

In [ ]:
store=pd.DataFrame(dataset,columns=["UNIXTime","Data","Time","Radiation","Temperature","Pressure","Humidity","WindDirection(Degrees)","Speed","TimeSunRise","TimeSunSet"])
store.to_csv("SolarPrediction_aligned_Sun.csv",index=False)